### ISSUE TITLE
parse rgb string doesn't work

### ISSUE THREAD

**Issue by getriebesand** [moagrius/Color#5]
In parse(value) if value is a rgb string, function p2v returns a string, but number is required for absround() later in format functions.

change
`	var p2v = function(p){
		return isPercent.test(p) ? absround(parseInt(p) * 2.55) : p;
	};`
to
`	var p2v = function(p){
		return isPercent.test(p) ? absround(parseInt(p) * 2.55) : parseInt(p);
	};`
will fix this issue

**Comment by moagrius** [comment]
awesome, thanks, will commit the change when i have some time

**Comment by moagrius** [comment]
fixed in https://github.com/moagrius/Color/pull/6
